# Generated by Django 4.2.3 on 2023-08-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisi_app', '0002_cart_category_photos_products_user_delete_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
